// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using bookingSystemZBC.Data;

#nullable disable

namespace bookingSystemZBC.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260426190430_AddUsersAndEmailIndexes")]
    partial class AddUsersAndEmailIndexes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("bookingSystemZBC.Domain.Entities.Activities.Activity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ActivityType")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("AdditionalInfoField1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaxParticipants")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Activities");

                    b.HasDiscriminator<string>("ActivityType").HasValue("Activity");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("bookingSystemZBC.Domain.Entities.ActivitySession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ActivityId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndTimeUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("LocationId")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<DateTime>("StartTimeUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ActivityId");

                    b.HasIndex("LocationId");

                    b.ToTable("ActivitySessions");
                });

            modelBuilder.Entity("bookingSystemZBC.Domain.Entities.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ActivitySessionId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("MemberId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ActivitySessionId");

                    b.HasIndex("MemberId", "ActivitySessionId")
                        .IsUnique();

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("bookingSystemZBC.Domain.Entities.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.HasKey("Id");

                    b.ToTable("Locations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Capacity = 0,
                            Description = "Large multi-purpose hall",
                            IsAvailable = true,
                            Name = "Main Hall"
                        },
                        new
                        {
                            Id = 2,
                            Capacity = 0,
                            Description = "Indoor swimming pool",
                            IsAvailable = true,
                            Name = "Pool Area"
                        });
                });

            modelBuilder.Entity("bookingSystemZBC.Domain.Entities.Member", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Members");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 26,
                            Email = "alice@example.com",
                            Name = "Alice Jensen"
                        },
                        new
                        {
                            Id = 2,
                            Age = 31,
                            Email = "bob@example.com",
                            Name = "Bob Nielsen"
                        });
                });

            modelBuilder.Entity("bookingSystemZBC.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<int?>("MemberId")
                        .HasColumnType("int");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("MemberId")
                        .IsUnique()
                        .HasFilter("[MemberId] IS NOT NULL");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("bookingSystemZBC.Domain.Entities.Activities.ClimbingActivity", b =>
                {
                    b.HasBaseType("bookingSystemZBC.Domain.Entities.Activities.Activity");

                    b.HasDiscriminator().HasValue("Climbing");
                });

            modelBuilder.Entity("bookingSystemZBC.Domain.Entities.Activities.SwimmingActivity", b =>
                {
                    b.HasBaseType("bookingSystemZBC.Domain.Entities.Activities.Activity");

                    b.HasDiscriminator().HasValue("Swimming");
                });

            modelBuilder.Entity("bookingSystemZBC.Domain.Entities.Activities.YogaActivity", b =>
                {
                    b.HasBaseType("bookingSystemZBC.Domain.Entities.Activities.Activity");

                    b.Property<string>("AddtionalInfoField1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("Yoga");
                });

            modelBuilder.Entity("bookingSystemZBC.Domain.Entities.ActivitySession", b =>
                {
                    b.HasOne("bookingSystemZBC.Domain.Entities.Activities.Activity", "Activity")
                        .WithMany("Sessions")
                        .HasForeignKey("ActivityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("bookingSystemZBC.Domain.Entities.Location", "Location")
                        .WithMany("Sessions")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Activity");

                    b.Navigation("Location");
                });

            modelBuilder.Entity("bookingSystemZBC.Domain.Entities.Booking", b =>
                {
                    b.HasOne("bookingSystemZBC.Domain.Entities.ActivitySession", "ActivitySession")
                        .WithMany("Bookings")
                        .HasForeignKey("ActivitySessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("bookingSystemZBC.Domain.Entities.Member", "Member")
                        .WithMany("Bookings")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ActivitySession");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("bookingSystemZBC.Domain.Entities.User", b =>
                {
                    b.HasOne("bookingSystemZBC.Domain.Entities.Member", "Member")
                        .WithOne()
                        .HasForeignKey("bookingSystemZBC.Domain.Entities.User", "MemberId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Member");
                });

            modelBuilder.Entity("bookingSystemZBC.Domain.Entities.Activities.Activity", b =>
                {
                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("bookingSystemZBC.Domain.Entities.ActivitySession", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("bookingSystemZBC.Domain.Entities.Location", b =>
                {
                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("bookingSystemZBC.Domain.Entities.Member", b =>
                {
                    b.Navigation("Bookings");
                });
#pragma warning restore 612, 618
        }
    }
}
