// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using bookingSystemZBC.Data;

#nullable disable

namespace bookingSystemZBC.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("UserRoles", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            RoleId = 2
                        },
                        new
                        {
                            UserId = 2,
                            RoleId = 1
                        },
                        new
                        {
                            UserId = 3,
                            RoleId = 1
                        },
                        new
                        {
                            UserId = 4,
                            RoleId = 1
                        });
                });

            modelBuilder.Entity("bookingSystemZBC.Domain.Entities.Activities.Activity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ActivityType")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("AdditionalInfoField1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaxParticipants")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Activities");

                    b.HasDiscriminator<string>("ActivityType").HasValue("Activity");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("bookingSystemZBC.Domain.Entities.ActivitySession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ActivityId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndTimeUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("LocationId")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<DateTime>("StartTimeUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ActivityId");

                    b.HasIndex("LocationId");

                    b.ToTable("ActivitySessions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ActivityId = 1,
                            EndTimeUtc = new DateTime(2026, 5, 4, 17, 0, 0, 0, DateTimeKind.Utc),
                            LocationId = 1,
                            Notes = "Bring your own mat if you prefer.",
                            StartTimeUtc = new DateTime(2026, 5, 4, 16, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2,
                            ActivityId = 2,
                            EndTimeUtc = new DateTime(2026, 5, 5, 18, 30, 0, 0, DateTimeKind.Utc),
                            LocationId = 2,
                            Notes = "Meet at the pool entrance 10 minutes before start.",
                            StartTimeUtc = new DateTime(2026, 5, 5, 17, 30, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 3,
                            ActivityId = 3,
                            EndTimeUtc = new DateTime(2026, 5, 6, 17, 0, 0, 0, DateTimeKind.Utc),
                            LocationId = 3,
                            Notes = "Harnesses are provided.",
                            StartTimeUtc = new DateTime(2026, 5, 6, 15, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 4,
                            ActivityId = 1,
                            EndTimeUtc = new DateTime(2026, 5, 7, 8, 30, 0, 0, DateTimeKind.Utc),
                            LocationId = 1,
                            Notes = "Quiet morning session.",
                            StartTimeUtc = new DateTime(2026, 5, 7, 7, 30, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("bookingSystemZBC.Domain.Entities.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ActivitySessionId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("MemberId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ActivitySessionId");

                    b.HasIndex("MemberId", "ActivitySessionId")
                        .IsUnique();

                    b.ToTable("Bookings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ActivitySessionId = 1,
                            CreatedAtUtc = new DateTime(2026, 4, 28, 9, 0, 0, 0, DateTimeKind.Utc),
                            MemberId = 1
                        },
                        new
                        {
                            Id = 2,
                            ActivitySessionId = 2,
                            CreatedAtUtc = new DateTime(2026, 4, 28, 9, 15, 0, 0, DateTimeKind.Utc),
                            MemberId = 2
                        },
                        new
                        {
                            Id = 3,
                            ActivitySessionId = 3,
                            CreatedAtUtc = new DateTime(2026, 4, 28, 9, 30, 0, 0, DateTimeKind.Utc),
                            MemberId = 3
                        },
                        new
                        {
                            Id = 4,
                            ActivitySessionId = 4,
                            CreatedAtUtc = new DateTime(2026, 4, 28, 9, 45, 0, 0, DateTimeKind.Utc),
                            MemberId = 1
                        });
                });

            modelBuilder.Entity("bookingSystemZBC.Domain.Entities.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.HasKey("Id");

                    b.ToTable("Locations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Capacity = 60,
                            Description = "Large multi-purpose hall",
                            IsAvailable = true,
                            Name = "Main Hall"
                        },
                        new
                        {
                            Id = 2,
                            Capacity = 30,
                            Description = "Indoor swimming pool",
                            IsAvailable = true,
                            Name = "Pool Area"
                        },
                        new
                        {
                            Id = 3,
                            Capacity = 24,
                            Description = "Indoor climbing wall with instructor area",
                            IsAvailable = true,
                            Name = "Climbing Wall"
                        });
                });

            modelBuilder.Entity("bookingSystemZBC.Domain.Entities.Member", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Members");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 26,
                            Email = "alice@example.com",
                            Name = "Alice Jensen"
                        },
                        new
                        {
                            Id = 2,
                            Age = 31,
                            Email = "bob@example.com",
                            Name = "Bob Nielsen"
                        },
                        new
                        {
                            Id = 3,
                            Age = 22,
                            Email = "clara@example.com",
                            Name = "Clara Madsen"
                        });
                });

            modelBuilder.Entity("bookingSystemZBC.Domain.Entities.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RoleId");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            RoleName = "User"
                        },
                        new
                        {
                            RoleId = 2,
                            RoleName = "Admin"
                        });
                });

            modelBuilder.Entity("bookingSystemZBC.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<int?>("MemberId")
                        .HasColumnType("int");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("MemberId")
                        .IsUnique()
                        .HasFilter("[MemberId] IS NOT NULL");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "admin@example.com",
                            FirstName = "System",
                            Password = "Admin123!",
                            Surname = "Administrator",
                            UserName = "admin"
                        },
                        new
                        {
                            Id = 2,
                            Email = "alice@example.com",
                            FirstName = "Alice",
                            MemberId = 1,
                            Password = "Password123!",
                            Surname = "Jensen",
                            UserName = "alice"
                        },
                        new
                        {
                            Id = 3,
                            Email = "bob@example.com",
                            FirstName = "Bob",
                            MemberId = 2,
                            Password = "Password123!",
                            Surname = "Nielsen",
                            UserName = "bob"
                        },
                        new
                        {
                            Id = 4,
                            Email = "clara@example.com",
                            FirstName = "Clara",
                            MemberId = 3,
                            Password = "Password123!",
                            Surname = "Madsen",
                            UserName = "clara"
                        });
                });

            modelBuilder.Entity("bookingSystemZBC.Domain.Entities.Activities.ClimbingActivity", b =>
                {
                    b.HasBaseType("bookingSystemZBC.Domain.Entities.Activities.Activity");

                    b.HasDiscriminator().HasValue("Climbing");

                    b.HasData(
                        new
                        {
                            Id = 3,
                            AdditionalInfoField1 = "Instructor included",
                            Level = "Beginner",
                            MaxParticipants = 12,
                            Name = "Intro Climbing",
                            Price = 125m,
                            Type = 2
                        });
                });

            modelBuilder.Entity("bookingSystemZBC.Domain.Entities.Activities.SwimmingActivity", b =>
                {
                    b.HasBaseType("bookingSystemZBC.Domain.Entities.Activities.Activity");

                    b.HasDiscriminator().HasValue("Swimming");

                    b.HasData(
                        new
                        {
                            Id = 2,
                            AdditionalInfoField1 = "Lane training",
                            Level = "Intermediate",
                            MaxParticipants = 16,
                            Name = "Evening Swim",
                            Price = 95m,
                            Type = 1
                        });
                });

            modelBuilder.Entity("bookingSystemZBC.Domain.Entities.Activities.YogaActivity", b =>
                {
                    b.HasBaseType("bookingSystemZBC.Domain.Entities.Activities.Activity");

                    b.Property<string>("AddtionalInfoField1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("Yoga");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AdditionalInfoField1 = "Hatha flow",
                            Level = "Beginner",
                            MaxParticipants = 20,
                            Name = "Morning Yoga",
                            Price = 75m,
                            Type = 3,
                            AddtionalInfoField1 = "Hatha flow"
                        });
                });

            modelBuilder.Entity("UserRoles", b =>
                {
                    b.HasOne("bookingSystemZBC.Domain.Entities.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("bookingSystemZBC.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("bookingSystemZBC.Domain.Entities.ActivitySession", b =>
                {
                    b.HasOne("bookingSystemZBC.Domain.Entities.Activities.Activity", "Activity")
                        .WithMany("Sessions")
                        .HasForeignKey("ActivityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("bookingSystemZBC.Domain.Entities.Location", "Location")
                        .WithMany("Sessions")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Activity");

                    b.Navigation("Location");
                });

            modelBuilder.Entity("bookingSystemZBC.Domain.Entities.Booking", b =>
                {
                    b.HasOne("bookingSystemZBC.Domain.Entities.ActivitySession", "ActivitySession")
                        .WithMany("Bookings")
                        .HasForeignKey("ActivitySessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("bookingSystemZBC.Domain.Entities.Member", "Member")
                        .WithMany("Bookings")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ActivitySession");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("bookingSystemZBC.Domain.Entities.User", b =>
                {
                    b.HasOne("bookingSystemZBC.Domain.Entities.Member", "Member")
                        .WithOne()
                        .HasForeignKey("bookingSystemZBC.Domain.Entities.User", "MemberId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Member");
                });

            modelBuilder.Entity("bookingSystemZBC.Domain.Entities.Activities.Activity", b =>
                {
                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("bookingSystemZBC.Domain.Entities.ActivitySession", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("bookingSystemZBC.Domain.Entities.Location", b =>
                {
                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("bookingSystemZBC.Domain.Entities.Member", b =>
                {
                    b.Navigation("Bookings");
                });
#pragma warning restore 612, 618
        }
    }
}
